MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.3                   # [osx]
macos_min_version:         # [osx]
  - 11.0                   # [osx]
c_compiler_version:        # [linux]
  - 10                     # [linux] 
cgo_compiler_version:
  - 1.18


