{% set name = "kubernetes" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 073b77321812f26df6513c0ad0aef3a8b0c17f6281a186d515f5855ae009ea17  # [not win]

  url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
  fn: {{ name }}-client-{{ version }}.tar.gz  # [win]
  sha256: d7fdf0341efe3d6a80a295aae19874a4099644c7ddba5fa34bee3a6924e0840b  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
    - rsync  # [not win]

test:
  commands:
    - cloud-controller-manager --version  # [linux]
    - hyperkube help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kubectl --help
    - kubelet --help  # [not osx]

    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
