{% set name = "kubernetes" %}
{% set version = "1.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 90a9e05995e55bf1ca4febf3801a2db177e4f5eb57663a00459619fce3b71676  # [not win]
  patches:  # [not win]
    - 0001-unset-conda-go-compiler.diff  # [not win]

  url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
  sha256: 44fba51f45eea275ea880272d3448cf034bcbc9b853f404270da145e373a0510  # [win]

build:
  number: 0

requirements:
  run:
    - {{ pin_subpackage('kubernetes-client', exact=True) }}
    - {{ pin_subpackage('kubernetes-node', exact=True) }}  # [linux or win]
    - {{ pin_subpackage('kubernetes-server', exact=True) }}  # [linux]


test:
  commands:
    - kubectl

    - kubelet --help  # [linux or win]
    - kube-proxy --help  # [linux or win]
    - kubeadm --help  # [linux or win]

    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-scheduler --help  # [linux]

outputs:
  - name: {{ name }}-client
    script: client/build.sh
    test:
      script: client/test.sh
    requirements:
      build:
        - {{ compiler('cgo') }} 1.13  # [not win]
        - {{ compiler('c') }}  # [not win]
        - make  # [not win]
        - rsync  # [not win]
        - jq  # [not win]
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Kubernetes client binaries

  - name: {{ name }}-node
    script: node/build.sh
    test:
      script: node/test.sh
    requirements:
      build:
        - {{ compiler('cgo') }} 1.13  # [not win]
        - {{ compiler('c') }}  # [not win]
        - make  # [not win]
        - rsync  # [not win]
        - jq  # [not win]
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Kubernetes node binaries

  - name: {{ name }}-server
    script: server/build.sh
    test:
      script: server/test.sh
    requirements:
      build:
        - {{ compiler('cgo') }} 1.13  # [not win]
        - {{ compiler('c') }}  # [not win]
        - make  # [not win]
        - rsync  # [not win]
        - jq  # [not win]
      run:
        - {{ pin_subpackage('kubernetes-node', exact=True) }}
    about:
        license: Apache-2.0
        license_file: LICENSE
        summary: Kubernetes server binaries

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
