{% set name = "kubernetes" %}
{% set version = "1.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: k8s.io/kubernetes  # [not win]
    url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: 9dc072cb7fa2aeb4ed6ee5e22e0a18eb323898af1c490c3a526d969313c483b3  # [not win]

    url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
    sha256: e4426587c216137fb8d28eb7fbc6c46260aee76bd536b822f8af138174bcc7bf  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.11  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - rsync  # [not win]

test:
  commands:
    - cloud-controller-manager --version  # [linux]
    - hyperkube help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kubectl --help
    - kubelet --help  # [not osx]

    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: k8s.io/kubernetes/LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
